modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL="https://github.com/zbx1425/mtr-addon-template/issues"

[[mods]]
modId = "renfe"
version = "${version}"
displayName = "MTR Renfe Addon"
displayURL = "https://github.com/joseka911/MTR-Renfe"

authors = "Joseka"
description = "Renfe addon is now available for minecraft transit Railway Mod"
logoFile = "icon.png"

displayTest = "IGNORE_ALL_VERSION"

[[dependencies.renfe]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.renfe]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.renfe]]
modId = "architectury"
mandatory = true
versionRange = "[1.26.37,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.renfe]]
modId = "mtr"
mandatory = true
versionRange = "1.0"
ordering = "AFTER"
side = "BOTH"
